TK="szgTdCTbpJ_ikGzZV5AR"
USR="prgrmz07"
cd /gitcode_repo_home/
git clone https://$USR:$TK@gitcode.net/myz/fnHok/instrmj.git
git clone https://$USR:$TK@gitcode.net/myz/fnHok/codegraph_java__fnSytxHok.git
git clone https://$USR:$TK@gitcode.net/myz/fnHok_main.git
git clone https://$USR:$TK@gitcode.net/pubz/z01/miniblink49.git
git clone https://$USR:$TK@gitcode.net/pubz/gitgraph.js.git
git clone https://$USR:$TK@gitcode.net/pubz/chrome.git
git clone https://$USR:$TK@gitcode.net/pubz/senior_high_math/open_math/maxima.git
git clone https://$USR:$TK@gitcode.net/pubz/senior_high_math/open_math/reduce-algebra.git
git clone https://$USR:$TK@gitcode.net/pubz/senior_high_math/open_math/axiom.git
git clone https://$USR:$TK@gitcode.net/pubz/senior_high_math/open_math/sympy.git
git clone https://$USR:$TK@gitcode.net/pubz/senior_high_math/open_math/sage.git
git clone https://$USR:$TK@gitcode.net/pubz/senior_high_math/jch1011/vue3_admin_template-bj1.git
git clone https://$USR:$TK@gitcode.net/pubx/img-bed.git
git clone https://$USR:$TK@gitcode.net/pubx/gshm/gshmba.git
git clone https://$USR:$TK@gitcode.net/myz/bal_main.git
git clone https://$USR:$TK@gitcode.net/pubz/wiki.git
git clone https://$USR:$TK@gitcode.net/pubz/mat-idx.git
git clone https://$USR:$TK@gitcode.net/pubxx/sec-books-part1.git
git clone https://$USR:$TK@gitcode.net/pubxx/crk_repo.git
git clone https://$USR:$TK@gitcode.net/pubxx/pdf.git
git clone https://$USR:$TK@gitcode.net/pubx/51/stc89c52_dev_board.git
git clone https://$USR:$TK@gitcode.net/pubx/stm32/mini-dev-board.git
git clone https://$USR:$TK@gitcode.net/pubx/stm32/stm32f103c8t6-minisys-cnc.git
git clone https://$USR:$TK@gitcode.net/pubx/stm32/stm32f10x-gcc-make-introduction.git
git clone https://$USR:$TK@gitcode.net/pubx/stm32/stm32f103-template.git
git clone https://$USR:$TK@gitcode.net/pubz/llvm/llvm-pass/llvm-tutor.git
git clone https://$USR:$TK@gitcode.net/myz/malloc_hok/glibc_mallocHok_gdbScript.git
git clone https://$USR:$TK@gitcode.net/pubz/tinycc.git
git clone https://$USR:$TK@gitcode.net/pubx/jetbrains/jetbrains_crack.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/nrdybhu1-atlas-jekyll-theme.git
git clone https://$USR:$TK@gitcode.net/pubx/GitKraken_Krack.git
git clone https://$USR:$TK@gitcode.net/pubx/resume.git
git clone https://$USR:$TK@gitcode.net/pubx/openjdk/pub.git
git clone https://$USR:$TK@gitcode.net/myz/dork_fnhok/jdk19u.git
git clone https://$USR:$TK@gitcode.net/pubx/os/kalamangga-net/linux-1.0.git
git clone https://$USR:$TK@gitcode.net/pubx/openjdk/jdk.git
git clone https://$USR:$TK@gitcode.net/myz/fnHok/funcSyntxHok.git
git clone https://$USR:$TK@gitcode.net/pubz/frida_develop.git
git clone https://$USR:$TK@gitcode.net/pubz/hunterzju--llvm-tutorial.git
git clone https://$USR:$TK@gitcode.net/pubz/llvm-project.git
git clone https://$USR:$TK@gitcode.net/pubz/instrmj-output.git
git clone https://$USR:$TK@gitcode.net/pubz/senior_high_math/vue3_admin_template_service.git
git clone https://$USR:$TK@gitcode.net/pubz/senior_high_math/GGZX.git
git clone https://$USR:$TK@gitcode.net/myz/bal/nlohmann--json.git
git clone https://$USR:$TK@gitcode.net/myz/bal/yhirose--cpp-httplib.git
git clone https://$USR:$TK@gitcode.net/myz/bal/fmtlib-fmt.git
git clone https://$USR:$TK@gitcode.net/myz/bal/bash-simplify.git
git clone https://$USR:$TK@gitcode.net/myz/bal/clang-add-funcIdAsm.git
git clone https://$USR:$TK@gitcode.net/myz/bal/mit-6.828-2014-jos.git
git clone https://$USR:$TK@gitcode.net/myz/bal/mit-6.828-2018-jos.git
git clone https://$USR:$TK@gitcode.net/myz/bal/mit6.828-bysui.git
git clone https://$USR:$TK@gitcode.net/myz/bal/mit-jos-2014-clpsz.git
git clone https://$USR:$TK@gitcode.net/myz/bal/xv6-x86.git
git clone https://$USR:$TK@gitcode.net/myz/bal/xv6-riscv.git
git clone https://$USR:$TK@gitcode.net/myz/bal/hit-oslab-linux.git
git clone https://$USR:$TK@gitcode.net/myz/bal/oslab.git
git clone https://$USR:$TK@gitcode.net/myz/bal/bochs.git
git clone https://$USR:$TK@gitcode.net/analyze_code/clang-ctk.git
git clone https://$USR:$TK@gitcode.net/analyze_code/clang-plugin-add-brace.git
git clone https://$USR:$TK@gitcode.net/analyze_code/clang-plugin-base.git
git clone https://$USR:$TK@gitcode.net/pubx/ML.git
git clone https://$USR:$TK@gitcode.net/myz/bal/cmd-wrap.git
git clone https://$USR:$TK@gitcode.net/pubx/analyze_code/lldb_demo.git
git clone https://$USR:$TK@gitcode.net/pubx/analyze_code/code/linux-0.11_karottc.git
git clone https://$USR:$TK@gitcode.net/pubx/analyze_code/code/linux-0.11_yuan-xy.git
git clone https://$USR:$TK@gitcode.net/pubz/disk-recovery/sleuthkit.org/subThreadUpdateUi.git
git clone https://$USR:$TK@gitcode.net/pubz/disk-recovery/sleuthkit.org/idea_debug_autopsy.git
git clone https://$USR:$TK@gitcode.net/pubz/disk-recovery/sleuthkit.org/sleuthkit.git
git clone https://$USR:$TK@gitcode.net/pubz/disk-recovery/sleuthkit.org/autopsy.git
git clone https://$USR:$TK@gitcode.net/pubx/vip_video/vvsite.git
git clone https://$USR:$TK@gitcode.net/pubx/analyze_code/code/linux.git
git clone https://$USR:$TK@gitcode.net/pubx/analyze_code/linux_kernel_analyze.git
git clone https://$USR:$TK@gitcode.net/pubx/operating_system/real_time_operating_system/rodos.git
git clone https://$USR:$TK@gitcode.net/pubx/git_client/lazygit.git
git clone https://$USR:$TK@gitcode.net/pubx/git_client/gitui.git
git clone https://$USR:$TK@gitcode.net/pubx/analyze_code/hook_mem_alloc.git
git clone https://$USR:$TK@gitcode.net/pubz/valgrind-home/valgrind.git
git clone https://$USR:$TK@gitcode.net/pubz/valgrind-home/valgrind-plugin/taintgrind-target/psi4.git
git clone https://$USR:$TK@gitcode.net/pubz/valgrind-home/valgrind-plugin/taintgrind-target/eigen.git
git clone https://$USR:$TK@gitcode.net/pubz/valgrind-home/valgrind-plugin/taintgrind-target/8cc.git
git clone https://$USR:$TK@gitcode.net/pubz/valgrind-home/valgrind-plugin/taintgrind.git
git clone https://$USR:$TK@gitcode.net/pubx/analyze_code/analyze_clang_by_valgrind.git
git clone https://$USR:$TK@gitcode.net/pubx/analyze_code/analyze_clang_by_gdb.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/spring-boot-helper-2022-3p_18622-2022-4-3-305008.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/fast-request-2021-2p-16988-2023-1-2-301129.git
git clone https://$USR:$TK@gitcode.net/pubx/source_code_rewrite/block_var_log_cpp.git
git clone https://$USR:$TK@gitcode.net/pubx/source_code_rewrite/clang_plugin_demo/clang-tutor.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/drop-quick-request-src.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/quick-request-samples.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/bytecode-viewer.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/jar_decompiler/fernflower.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/jar_rename/rename_jarUSRsing_proguard.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/fast-request.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/jar_decompiler/cfr.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/jar_decompiler/procyon.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/wolfram-language.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/block_var_log.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/odoo.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/guardsquare/proguard.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/guardsquare/proguard-core.git
git clone https://$USR:$TK@gitcode.net/myz/idea_plugin_reverse/jar_refactor.git
git clone https://$USR:$TK@gitcode.net/pubx/spring-boot-example/spring-boot-rest-example-khoubyari.git
git clone https://$USR:$TK@gitcode.net/pubx/spring-boot-example/spring-boot-examples-in28minutes.git
git clone https://$USR:$TK@gitcode.net/pubx/spring-boot-example/spring-boot-examples-ityouknow.git
git clone https://$USR:$TK@gitcode.net/pubx/gitkraken/wcxo-gitcracken.git
git clone https://$USR:$TK@gitcode.net/pubx/gitkraken/GitCracken.git
git clone https://$USR:$TK@gitcode.net/pubx/adv_click_times_rnn.git
git clone https://$USR:$TK@gitcode.net/pubx/git-replace.git
git clone https://$USR:$TK@gitcode.net/pubx/delve.git
git clone https://$USR:$TK@gitcode.net/pubx/github-hosts.git
git clone https://$USR:$TK@gitcode.net/pubz/zslwyuan-llvm-11-tutorials.git
git clone https://$USR:$TK@gitcode.net/pubz/gcc.git

