| file_extend_name | cnt  |
|------------------|------|
| cpp              | 2026 |
| svg              | 1894 |
| h                | 1641 |
| py               | 1305 |
| ts               | 1016 |
| ui               | 402  |
| qm               | 348  |
| hxx              | 260  |
| xml              | 236  |
| txt              | 190  |
| FCMat            | 126  |
| cc               | 105  |
| hpp              | 85   |
| png              | 65   |
| md               | 64   |
| cmake            | 59   |
| inl              | 57   |
| dox              | 45   |
| stp              | 34   |
| nsh              | 34   |
| qrc              | 33   |
| json             | 33   |
| inp              | 33   |
| yml              | 31   |
| jt               | 30   |
|                  | 28   |
| FCStd            | 25   |
| fcstd            | 24   |
| brep             | 24   |
| qss              | 23   |
| dxf              | 19   |
| cfg              | 18   |
| rub              | 17   |
| sh               | 16   |
| csv              | 16   |
| c                | 13   |
| bat              | 13   |
| in               | 12   |
| cxx              | 12   |
| bdf              | 11   |
| xpm              | 10   |
| fctb             | 10   |
| zip              | 9    |
| html             | 8    |
| gitattributes    | 7    |
| dat              | 6    |
| bmp              | 6    |
| sif              | 5    |
| pdf              | 5    |
| ttf              | 4    |
| plmxml           | 4    |
| igs              | 4    |
| dyn              | 4    |
| y                | 3    |
| wrl              | 3    |
| patch            | 3    |
| l                | 3    |
| ico              | 3    |
| icns             | 3    |
| gitignore        | 3    |
| bazel            | 3    |
| yaml             | 2    |
| xsd              | 2    |
| vcxproj          | 2    |
| tmpl             | 2    |
| scss             | 2    |
| plist            | 2    |
| p21              | 2    |
| m                | 2    |
| license          | 2    |
| js               | 2    |
| htm              | 2    |
| frd              | 2    |
| fctl             | 2    |
| css              | 2    |
| conf             | 2    |
| clang-format     | 2    |
| FCMacro          | 2    |
