|                  file_extend_name                   | cnt  |
|-----------------------------------------------------|------|
| py                                                  | 4035 |
| h                                                   | 2607 |
| cpp                                                 | 1808 |
| cc                                                  | 945  |
| cu                                                  | 526  |
| txt                                                 | 303  |
| expect                                              | 250  |
| c                                                   | 196  |
| rst                                                 | 193  |
| sh                                                  | 167  |
| md                                                  | 164  |
| zip                                                 | 156  |
| glsl                                                | 111  |
| yml                                                 | 110  |
| pt                                                  | 106  |
| mm                                                  | 106  |
| ptl                                                 | 101  |
| cmake                                               | 85   |
| cuh                                                 | 70   |
| png                                                 | 59   |
| bzl                                                 | 59   |
| pyi                                                 | 57   |
| hpp                                                 | 42   |
|                                                     | 42   |
| csv                                                 | 41   |
| S                                                   | 34   |
| java                                                | 27   |
| in                                                  | 25   |
| yaml                                                | 20   |
| gitignore                                           | 18   |
| bat                                                 | 18   |
| BUILD                                               | 17   |
| bazel                                               | 16   |
| json                                                | 15   |
| xml                                                 | 14   |
| hip                                                 | 12   |
| ipynb                                               | 11   |
| ff                                                  | 10   |
| gradle                                              | 9    |
| test_non_iterable                                   | 7    |
| test_exceptions                                     | 7    |
| proto                                               | 7    |
| oss                                                 | 7    |
| jpg                                                 | 7    |
| css                                                 | 7    |
| imp                                                 | 6    |
| html                                                | 6    |
| test_axis                                           | 5    |
| properties                                          | 5    |
| j2                                                  | 5    |
| test_to                                             | 4    |
| svg                                                 | 4    |
| ini                                                 | 4    |
| typed                                               | 3    |
| toml                                                | 3    |
| test_stack                                          | 3    |
| test_simple                                         | 3    |
| test_profiler                                       | 3    |
| test_mm                                             | 3    |
| test_max                                            | 3    |
| test_matrix_2x2                                     | 3    |
| test_linear                                         | 3    |
| test_invalid                                        | 3    |
| test_inplace_metadata                               | 3    |
| test_conv2d                                         | 3    |
| test_basic                                          | 3    |
| test_bad_args                                       | 3    |
| test_0D_array                                       | 3    |
| template                                            | 3    |
| ps1                                                 | 3    |
| pb                                                  | 3    |
| gz                                                  | 3    |
| clang-format                                        | 3    |
| xcscheme                                            | 2    |
| test_with_dims_split                                | 2    |
| test_unrelated_output_cpu                           | 2    |
| test_unbind                                         | 2    |
| test_unary_ops                                      | 2    |
| test_transpose                                      | 2    |
| test_torch_to                                       | 2    |
| test_to_dtype                                       | 2    |
| test_split                                          | 2    |
| test_softmax_split                                  | 2    |
| test_slice                                          | 2    |
| test_sigmoid_cpu                                    | 2    |
| test_seg                                            | 2    |
| test_save_load                                      | 2    |
| test_reshape                                        | 2    |
| test_remove_output_used_only_in_size                | 2    |
| test_record_function                                | 2    |
| test_qlinear                                        | 2    |
| test_qat_update_shared_qspec                        | 2    |
| test_qat_preserve_source_fn_stack                   | 2    |
| test_qat_inplace_add_relu                           | 2    |
| test_qat_conv_no_bias                               | 2    |
| test_qat_conv_bn_relu_fusion_no_conv_bias           | 2    |
| test_qat_conv_bn_relu_fusion                        | 2    |
| test_qat_conv_bn_fusion_no_conv_bias                | 2    |
| test_qat_conv_bn_fusion_literal_args                | 2    |
| test_qat_conv_bn_fusion                             | 2    |
| test_prepare_qat_conv_bn_fusion_getitem_placeholder | 2    |
| test_permute_orig                                   | 2    |
| test_parse                                          | 2    |
| test_order_keyword                                  | 2    |
| test_order                                          | 2    |
| test_network                                        | 2    |
| test_mul_cpu                                        | 2    |
| test_monkey                                         | 2    |
| test_mm_fuse                                        | 2    |
| test_matmul                                         | 2    |
| test_mask                                           | 2    |
| test_manual_stuff                                   | 2    |
| test_make_fx_vjp_cpu                                | 2    |
| test_inplace                                        | 2    |
| test_index_placement                                | 2    |
| test_index_cpu                                      | 2    |
| test_index                                          | 2    |
| test_hello                                          | 2    |
| test_gelu                                           | 2    |
| test_functorch                                      | 2    |
| test_flatten                                        | 2    |
| test_finite_range                                   | 2    |
| test_extended_axis_invalid                          | 2    |
| test_expand                                         | 2    |
| test_execution                                      | 2    |
| test_example_inputs                                 | 2    |
| test_eq                                             | 2    |
| test_empty_input                                    | 2    |
| test_embed                                          | 2    |
| test_dynamic_linear                                 | 2    |
| test_doc                                            | 2    |
| test_dir                                            | 2    |
| test_dims_with_size                                 | 2    |
| test_dim_args                                       | 2    |
| test_diag                                           | 2    |
| test_compare_dims                                   | 2    |
| test_cat                                            | 2    |
| test_c                                              | 2    |
| test_big_split                                      | 2    |
| test_bad_axis_func1                                 | 2    |
| test_bad_axis_func0                                 | 2    |
| test_attn                                           | 2    |
| test_amp_cache                                      | 2    |
| test_add_cpu                                        | 2    |
| test_adapt                                          | 2    |
| test_1D_array                                       | 2    |
| storyboard                                          | 2    |
| service                                             | 2    |
| rb                                                  | 2    |
| plist                                               | 2    |
| patch                                               | 2    |
| mjs                                                 | 2    |
| m                                                   | 2    |
| lds                                                 | 2    |
| js                                                  | 2    |
| jpeg                                                | 2    |
| fbs                                                 | 2    |
| conf                                                | 2    |
| clang-tidy                                          | 2    |
